[phases.setup]
nixPkgs = ["python311", "gcc", "libmysqlclient"]

[phases.install]
cmds = ["python -m pip install --upgrade pip", "pip install -r requirements.txt"]

[phases.build]
cmds = ["python manage.py collectstatic --noinput"]

[start]
cmd = "gunicorn Book.wsgi --log-file -"
