[build]
builder = "heroku-buildpack-python"

[deploy]
startCommand = "cd Book && gunicorn BookNova.wsgi --log-file -"
buildCommand = "pip install -r requirements.txt && cd Book && python manage.py collectstatic --noinput"
releasesEnabled = true
