[phases.setup]
nixPkgs = ["python39", "gcc", "libmysqlclient"]
providers = ["python"]

[phases.install]
cmds = ["pip install --upgrade pip setuptools wheel", "pip install -r requirements.txt"]

[phases.build]
cmds = ["cd Book && python manage.py collectstatic --noinput"]

[start]
cmd = "cd Book && gunicorn BookNova.wsgi --log-file -"
watchPatterns = ["Book/**/*.py"]
